# Konflux does not only support running builds in containers locally but also supports running builds
# in remote VMs with the multi-platform controller. In order to simplify the specification of build
# targets, however, we are adding support for the multi-platform controller to also be able to build
# in-cluseter with the tasks focused on building remotely. Therefore, we need to maintain a buildah image
# for our tasks that has more than _just_ buildah in it. We also need to add the required functionality
# for the remote builds.

FROM registry.access.redhat.com/ubi10/ubi-minimal@sha256:a74a7a92d3069bfac09c6882087771fc7db59fa9d8e16f14f4e012fe7288554c AS dep-builder

ARG BUILDER_RPMS="golang make rsync"
RUN microdnf install -y $BUILDER_RPMS

ENV GOPROXY='https://proxy.golang.org,direct'
ENV GOSUMDB='sum.golang.org'

WORKDIR /app
COPY dockerfile-json dockerfile-json

WORKDIR /app/dockerfile-json
RUN go build -tags=dfrunsecurity -o dockerfile-json

FROM quay.io/konflux-ci/task-runner:1.2.0@sha256:fbfcb48f2d05e7436830382c7ba079493d3426f5ebdffa4b87fee4229551d4c0

LABEL \
    org.opencontainers.image.url="https://quay.io/konflux-ci/buildah-task" \
    org.label-schema.name="buildah-task" \
    org.opencontainers.image.title="buildah-task" \
    name="konflux-buildah-task" \
    com.redhat.component="konflux-buildah-task" \
    io.k8s.display-name="konflux-buildah-task" \
    io.openshift.tags="buildah tekton" \
    summary="Command line tool to create and work with containers within Tekton tasks." \
    description="Command line tool to create and work with containers. This is a repackaged version for use within Tekton tasks in Konflux CI. It includes additional functionality on top of buildah that might be required for the tasks." \
    io.k8s.description="Command line tool to create and work with containers. This is a repackaged version for use within Tekton tasks in Konflux CI. It includes additional functionality on top of buildah that might be required for the tasks."

USER 0

ARG INSTALL_RPMS="rsync openssh-clients iproute subscription-manager openssl-libs"
RUN microdnf install -y $INSTALL_RPMS && \
    microdnf -y clean all && \
    rm -rf /var/cache /var/log/dnf* /var/log/yum.*
COPY --from=dep-builder /app/dockerfile-json/dockerfile-json /usr/bin
COPY scripts/icm-injection-scripts/inject-icm.sh /usr/bin/inject-icm-to-containerfile

# Note: the retry script isn't necessary anymore, because the task-runner image has
# /usr/local/bin/retry with near-compatible behavior. To be fully compatible, it just
# needs the RETRY_STOP_IF_STDERR_MATCHES=unauthorized environment variable, which is set
# in the task-runner base image.
#
# However, other quay.io/konflux-ci images use the 'COPY --from' trick to copy the retry
# script from the buildah image, so we have to keep it here for now.
COPY scripts/utils/retry-func.sh /usr/bin/retry
RUN chmod +x /usr/bin/retry

RUN echo '{"default":[{"type": "insecureAcceptAnything"}],"transports":{"docker-daemon":{"":[{"type":"insecureAcceptAnything"}]}}}' > /etc/containers/policy.json
